### ISSUE TITLE
Wrong Month being displayed on calendar

### ISSUE THREAD

**Issue by NPrice99** [OlivierCC/spfx-custom-fields#1]
Hi

To get 7th September 2016 to display in the webpart, In the properties date field I have to select 7th October 2016.  (See attached file)

Regards

Nigel

[custom-fields-evidence.docx](https://github.com/OlivierCC/spfx-custom-fields/files/459184/custom-fields-evidence.docx)

**Comment by OlivierCC** [comment]
Thx for this reporting, I will investigate this bug

**Comment by OlivierCC** [comment]
Thanks again Nigel for this report. This bug is now fix. It happened for every month after March, because was forgotten in the month list. If now fix with in the current commit. Regards,
